# Generated by Django 5.0.2 on 2024-02-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr_api', '0002_auto_20240222_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='commission',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Any')], default=2),
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.ManyToManyField(blank=True, to='ihr_api.country'),
        ),
    ]
