# Generated by Django 5.0.2 on 2024-02-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr_api', '0003_country_store_commission_alter_product_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male'), (2, 'Any')], default=2, null=True),
        ),
    ]
