# Generated by Django 5.0.2 on 2024-02-28 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ihr_api', '0005_payment_sale_saleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='store',
        ),
    ]
