# Generated by Django 5.0.2 on 2024-03-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr_api', '0006_remove_category_store_remove_subcategory_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='first_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='last_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='phone_number',
            field=models.CharField(default=111111111, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open Pay'), (1, 'Apple Pay'), (2, 'Mercadopago'), (3, 'Crypto')], default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='indications',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
