# Generated by Django 5.0.2 on 2024-03-10 20:26

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr_api', '0006_remove_category_store_remove_subcategory_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('size', models.IntegerField(default=0)),
                ('source', models.FileField(blank=True, max_length=300, null=True, upload_to='product_images/')),
                ('source_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='first_name',
            field=models.CharField(default='firstname', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='last_name',
            field=models.CharField(default='lastname', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='phone_number',
            field=models.CharField(default='924924924', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open Pay'), (1, 'Apple Pay'), (2, 'Mercadopago'), (3, 'Crypto')], default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='indications',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ihr_api.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='products', to='ihr_api.image'),
        ),
    ]
