# Generated by Django 5.0.2 on 2024-03-10 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr_api', '0007_sale_first_name_sale_last_name_sale_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(0, 'Open Pay'), (1, 'Apple Pay'), (2, 'Mercadopago'), (3, 'Crypto')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_dollars',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ihr_api.currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
