# Generated by Django 5.0.2 on 2024-03-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr_api', '0009_billingaccount_key_1_billingaccount_key_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
