# Generated by Django 5.0.2 on 2024-03-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr_api', '0010_billingaccount_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
