# Generated by Django 5.0.2 on 2024-03-11 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihr_api', '0012_payment_billing_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='billing_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ihr_api.billingaccount'),
        ),
    ]
